services:
  aquainsure:
    image: ghcr.io/quantxai-pvt-ltd/aquawebapp-aquainsure:latest
    build:
      context: ./AquaInsure
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    restart: unless-stopped
    depends_on:
      - aquainsurebackend

  aquainsurebackend:
    image: ghcr.io/quantxai-pvt-ltd/aquawebapp-aquainsurebackend:latest
    build:
      context: ./AquaInsurebackend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: unless-stopped
    env_file:
      - ./AquaInsurebackend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dashboard:
    image: ghcr.io/quantxai-pvt-ltd/aquawebapp-aquainsuredashboard:latest
    build:
      context: ./Aquainsuredashboard
      dockerfile: Dockerfile
    ports:
      - "5002:3000"
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - aquainsurebackend
    extra_hosts:
      - "host.docker.internal:host-gateway"
